### PR TITLE
Add timing properties as per ATMakersBill's suggestion

### PR DESCRIPTION
**Pull request by dastels**

### CODE REVIEW

**Comment by ATMakersBill** [comment]
My only comment would be to add an example that uses the duration properties.  Otherwise, this is great.

**Comment by tannewt** [comment]
Where is the context for this PR? I'm ok adding this but would love to understand the motivation before doing the review.

**Comment by dastels** [comment]
@tannewt This was a request from @ATMakersBill: to give timing information to make it easier to detect short vs long presses (for example).

**Review by tannewt — APPROVED** [review]
Cool. Works for me. Thanks!

**Pull request merged**
